## USAGE: ORDER (2)
## Purpose:
## This CloudFormation protects the dynamodb table and resources from being deleted when it 
## is removed from the cloudformation template.
## Changes:
## - ADD a DeltionPolicy: Retain to dynamoDB
## - ADD MyEmptyResource in preperation for the unmanage step
## - ADD DeletionProtectionEnabled: true to Properties
## - ADD DisableScaleIn: false to tableReadScalingPolicy and tableWriteScalingPolicy


AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DBTableName: 
    Type: String
    Default: cfnTestPrices
    Description: Should be the table name to test
Resources:
  cfnTestPrices:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Ref DBTableName
      DeletionProtectionEnabled: true
      AttributeDefinitions:
      - AttributeName: priceId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: priceId
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      StreamSpecification:
            StreamViewType: "KEYS_ONLY"

  TableWriteCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      DeletionPolicy: Retain
      Properties:
          MaxCapacity: 20 
          MinCapacity: 10 
          ResourceId: !Join
                    - ''
                    - - 'table/'
                      - !Ref DBTableName
          RoleARN: !Join 
                    - ''
                    - - 'arn:aws:iam::'
                      - !Ref AWS::AccountId
                      - ':role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable'
          ScalableDimension: dynamodb:table:WriteCapacityUnits
          ServiceNamespace: dynamodb
      DependsOn: cfnTestPrices

  TableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DeletionPolicy: Retain
    Properties:
        PolicyName: TableWriteScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId: !Ref TableWriteCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
            TargetValue: 70.0
            ScaleInCooldown: 61
            ScaleOutCooldown: 61
            DisableScaleIn: false
            PredefinedMetricSpecification:
                PredefinedMetricType: DynamoDBWriteCapacityUtilization
    DependsOn: cfnTestPrices

  TableReadCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      DeletionPolicy: Retain
      Properties:
          MaxCapacity: 20
          MinCapacity: 10
          ResourceId: !Join
                    - ''
                    - - 'table/' 
                      - !Ref DBTableName
          RoleARN: !Join 
                    - ''
                    - - 'arn:aws:iam::'
                      - !Ref AWS::AccountId
                      - ':role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable'
          ScalableDimension: dynamodb:table:ReadCapacityUnits
          ServiceNamespace: dynamodb
      DependsOn: cfnTestPrices

  TableReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DeletionPolicy: Retain
    Properties:
        PolicyName: TableReadScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId: !Ref TableReadCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
            TargetValue: 70.0
            ScaleInCooldown: 50
            ScaleOutCooldown: 50
            DisableScaleIn: false
            PredefinedMetricSpecification:
                PredefinedMetricType: DynamoDBReadCapacityUtilization
    DependsOn: cfnTestPrices

  MyEmptyResource:
    Type: AWS::CloudFormation::WaitConditionHandle