## USAGE: ORDER (5)
## Purpose:
## This step creates a replica in us-east-2 with the inital same read values.
## This step can take a while while replicating data to the other region.
## Changes:
## ADD an additional replica in ReplicaRegion
## ADD Parameter for ReplicaRegion


AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DBTableName: 
    Type: String
    Default: CfnTestPrices
    Description: Should be the table name to test
  PrimaryRegion: 
    Type: String
    Default: us-east-1
    Description: Region Primary Table is located
  ReplicaRegion: 
    Type: String
    Default: us-east-2
    Description: Region replica is located
Resources:
  CfnTestPrices:
    Type: AWS::DynamoDB::GlobalTable
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Ref DBTableName
      BillingMode: "PROVISIONED"
      AttributeDefinitions:
      - AttributeName: priceId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: priceId
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      StreamSpecification:
            StreamViewType: "KEYS_ONLY"
      WriteProvisionedThroughputSettings:
        WriteCapacityAutoScalingSettings:
          MaxCapacity: 20
          MinCapacity: 10
          TargetTrackingScalingPolicyConfiguration: 
            TargetValue: 70.0
            ScaleInCooldown: 61
            ScaleOutCooldown: 61
            DisableScaleIn: false
      Replicas:
       - 
        Region: !Ref PrimaryRegion
        DeletionProtectionEnabled: true
        ReadProvisionedThroughputSettings:
          ReadCapacityAutoScalingSettings:
            MaxCapacity: 20 
            MinCapacity: 10  
            TargetTrackingScalingPolicyConfiguration:
              ScaleInCooldown: 50 
              ScaleOutCooldown: 50
              TargetValue: 70.0
              DisableScaleIn: false
       - 
        Region: !Ref ReplicaRegion
        DeletionProtectionEnabled: true
        ReadProvisionedThroughputSettings:
          ReadCapacityAutoScalingSettings:
            MaxCapacity: 20
            MinCapacity: 10
            TargetTrackingScalingPolicyConfiguration:
              ScaleInCooldown: 50
              ScaleOutCooldown: 50
              TargetValue: 70.0
              DisableScaleIn: false
